image: node:16.15.1

before_script:
  - npm install
  - npm ci

cache:
  untracked: true
  paths:
    - node_modules/

stages:
  - setup
  - test
  - build
  - deploy

setup:
  stage: setup
  script:
    - echo "Setting up build ..."
    - npm run build
  only:
    - master

test:
  stage: test
  script:
    - echo "Doing some test ..."
    - npm run test
  only:
    - master

build:
  stage: build
  script:
    - echo "Building artifacts ..."
    - npm run generate
  artifacts:
    expire_in: 4 week
    paths:
      - dist
  only:
    - master

deploy:
  stage: deploy
  environment:
    name: production
    url: https://hubad-na-balita.netlify.app
  script:
    - echo "Deploy to production server"
    - npm i netlify-cli --location=global
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  dependencies:
    - build
  only:
    - master
  when: manual