image: node:latest

before_script:
  - npm install

stages:
  - setup
  - test
  - build
  - deploy

setup:
  stage: setup
  script:
    - echo "Setting up the build"
    - npm ci
  only:
    - master

test:
  stage: test
  script:
    - echo "Doing some test"
    - npm run test
  only:
    - master

build:
  stage: build
  script:
    - echo "Building artifacts"
    - npm run generate
  artifacts:
    expire_in: 4 week
    paths:
      - dist
  only:
    - master

deploy:
  stage: deploy
  environment:
    name: production
    url: https://nuxt-demo-netlify.netlify.app
  script:
    - echo "Deploy to production server"
    - npm i -g netlify-cli
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  dependencies:
    - build
  only:
    - master
  when: manual


