image: node:16.15.1

before_script:
  - yarn

stages:
  - build
  - test
  - generate

build:
  stage: build
  script:
    - echo "Setting up the build"
    - yarn build
  only:
    - master

test:
  stage: test
  script:
    - echo "Doing some test"
    - yarn test
  only:
    - master

generate:
  stage: generate
  script:
    - echo "Generate artifacts"
    - yarn generate
  artifacts:
    expire_in: 4 week
    paths:
      - dist
  only:
    - master
