image: node

before_script:
  - npm install

stages:
  - setup
  - test
  - build

setup:
  stage: setup
  script:
    - echo "Setting up the build"
    - npm run build

test:
  stage: test
  script:
    - echo "Doing some test"
    - npm run test

build:
  stage: build
  script:
    - echo "Building artifacts"
    - npm run generate
  artifacts:
    expire_in: 1 week
    paths:
      - dist


