image: node

before_script:
  - npm install

stages:
  - setup
  - test

setup:
  stage: setup
  script:
    - echo "Setting up the build"
    - npm run build

test:
  stage: test
  script:
    - echo "Doing some test"
    - npm run test

