image: node:16.15.1

before_script:
  - npm install

stages:
  - setup
  - test
  - build
  - generate
  - deploy

setup:
  stage: setup
  script:
    - echo "Setting up..."
    - npm ci
  only:
    - master

test:
  stage: test
  script:
    - echo "Doing some test ..."
    - npm run test
  only:
    - master

build:
  stage: build
  script:
    - echo "Building ..."
    - npm run build
  only:
    - master

generate:
  stage: generate
  script:
    - echo "Generate artifact ..."
    - npm run generate
  artifacts:
    expire_in: 4 week
    paths:
      - dist
  only:
    - master

deploy:
  stage: deploy
  environment:
    name: production
    url: https://hubad-na-balita.netlify.app
  script:
    - echo "Deploy to production server"
    - npm install netlify-cli -g
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  dependencies:
    - build
  only:
    - master
