image: node:16.15.1

before_script:
  - yarn

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Setting up the build"
    - yarn build
  only:
    - master

test:
  stage: test
  script:
    - echo "Doing some test"
    - yarn test
  only:
    - master
