image: node

before_script:
  - npm install

cache:
  paths:
    - node_modules/

build site:
  stage: build
  script:
    - npm run build

unit test:
  stage: test
  script:
    - npm run test

deploy:
  stage: deploy
  script:
    - npm run generate
  artifacts:
    expire_in: 4 week
    paths:
      - public
  only:
    - master
